version: '3.8'

services:
  agenttorch-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agenttorch-mcp
    volumes:
      # Mount your data and configuration files
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
      - ./config.yaml:/app/config.yaml
      # Optional: Mount server.py for development without rebuilding
      - ./server.py:/app/server.py
    ports:
      # WebSocket port for UI communication
      - "8765:8765"
      # HTTP port for serving the UI
      - "8080:8080"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHONPATH=/app
      - AGENTTORCH_CONFIG_PATH=/app/config.yaml
      # Set server mode: full, web, mcp, or websocket
      - SERVER_MODE=full
      # Optional: Set debug mode for development
      - DEBUG=false
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped